from funcionesIngreso import es_numero

print("Pruebas con numeros:")
print(es_numero(5))
print(es_numero(3.14))
print(es_numero(-10))
print(es_numero(0))
print(es_numero(1000000))
print(es_numero(-3.14159))

print("Pruebas con strings validos:")
print(es_numero("123"))
print(es_numero("456789"))
print(es_numero("0"))
print(es_numero("13456789"))
print(es_numero("999999"))

print("Pruebas con strings invalidos:")
print(es_numero("abc"))
print(es_numero("12a"))
print(es_numero("1.5"))
print(es_numero("-123"))
print(es_numero(""))
print(es_numero(" "))
print(es_numero("12 34"))
print(es_numero("!@#"))
print(es_numero("2"))

print("Pruebas con otros tipos:")
print(es_numero(True))
print(es_numero(False))
print(es_numero(None))
print(es_numero([1, 2, 3]))
print(es_numero({"numero": 5}))
print(es_numero(1 + 2j))